platform :ios, '5.0'
pod 'AFNetworking', '~> 1.3.3'

platform :ios, '6.0' 
pod 'DBCamera', '~> 1.0'

platform :ios, '7.0'
pod 'ionicons'
pod 'DropdownMenu'
pod 'MHVideoPhotoGallery'
pod 'ECSlidingViewController', '~> 1.3.3'
